[[layout.rows]]
height = 15
slots = [
    { width = 100, widget = "sistema" },
]

[[layout.rows]]
height = 70
slots = [
    { width = 70, widget = "noticias" },
    { width = 30, widget = "clima" },
]

[[layout.rows]]
height = 15
slots = [
    { width = 50, widget = "dolar" },
    { width = 50, widget = "btc" },
]

[widgets.sistema]
kind = "sistema"

[widgets.clima]
kind     = "weather"
location = "Buenos Aires,AR"
api_key  = "35c42a703bf25abc96befb1a724fa0a5"
ttl_secs = 600

[widgets.noticias]
kind      = "rss"
url       = "https://www.infobae.com/arc/outboundfeeds/rss/"
max_items = 12
ttl_secs  = 300
tts_cmd   = "ESPEAK_DATA_PATH=/home/leandro/.local/share/piper/espeak-ng-data piper --model /home/leandro/.local/share/piper/voices/es_ES-davefx-medium.onnx --output-raw | aplay -r 22050 -f S16_LE -c 1 -t raw -q"

[widgets.dolar]
kind     = "dolar"
ttl_secs = 300

[widgets.btc]
kind     = "btc"
ttl_secs = 60

[theme]
accent       = "#ffb000"
accent_focus = "#4af626"
inactive     = "#3a2000"
border_type  = "plain"

[theme.widget_accents]
sistema  = "#ffb000"
clima    = "#cc8800"
noticias = "#ffaa00"
dolar    = "#ffcc00"
btc      = "#ff9a00"
